/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.jdbc;

import com.wsr.dao.*;
import com.wsr.factory.*;
import com.wsr.dto.*;
import com.wsr.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class NamespacesDaoImpl extends AbstractDAO implements NamespacesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ns_id, namespace FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ns_id, namespace ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ns_id = ?, namespace = ? WHERE ns_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ns_id = ?";

	/** 
	 * Index of column ns_id
	 */
	protected static final int COLUMN_NS_ID = 1;

	/** 
	 * Index of column namespace
	 */
	protected static final int COLUMN_NAMESPACE = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column ns_id
	 */
	protected static final int PK_COLUMN_NS_ID = 1;

	/** 
	 * Inserts a new row in the namespaces table.
	 */
	public NamespacesPk insert(Namespaces dto) throws NamespacesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getNsId() );
			stmt.setString( index++, dto.getNamespace() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setNsId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}catch (Throwable _e) {
			throw new NamespacesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the namespaces table.
	 */
	public void update(NamespacesPk pk, Namespaces dto) throws NamespacesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getNsId() );
			stmt.setString( index++, dto.getNamespace() );
			stmt.setInt( 3, pk.getNsId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Throwable _e) {
			throw new NamespacesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the namespaces table.
	 */
	public void delete(NamespacesPk pk) throws NamespacesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getNsId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		}
		catch (Throwable _e) {
			throw new NamespacesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the namespaces table that matches the specified primary-key value.
	 */
	public Namespaces findByPrimaryKey(NamespacesPk pk) throws NamespacesDaoException
	{
		return findByPrimaryKey( pk.getNsId() );
	}

	/** 
	 * Returns all rows from the namespaces table that match the criteria 'ns_id = :nsId'.
	 */
	public Namespaces findByPrimaryKey(int nsId) throws NamespacesDaoException
	{
		Namespaces ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ns_id = ?", new Object[] {  new Integer(nsId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the namespaces table that match the criteria ''.
	 */
	public Namespaces[] findAll() throws NamespacesDaoException
	{
		return findByDynamicSelect( SQL_SELECT, null );
	}

	/** 
	 * Returns all rows from the namespaces table that match the criteria 'ns_id = :ns_id'.
	 */
	public Namespaces findByNS_ID(int ns_id) throws NamespacesDaoException
	{
		Namespaces ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ns_id = ?", new Object[] {  new Integer(ns_id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the namespaces table that match the criteria 'namespace = :namespace'.
	 */
	public Namespaces findByNamespace(String namespace) throws NamespacesDaoException
	{
		Namespaces ret[] = findByDynamicSelect( SQL_SELECT + " WHERE namespace = ?", new Object[] { namespace } );
		return ret.length==0 ? null : ret[0];
	}

	/**
	 * Method 'NamespacesDaoImpl'
	 * 
	 */
	public NamespacesDaoImpl()
	{
	}

	/**
	 * Method 'NamespacesDaoImpl'
	 * 
	 * @param userConn
	 */
	public NamespacesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "webservicerank.namespaces";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Namespaces fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Namespaces dto = new Namespaces();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Namespaces[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Namespaces dto = new Namespaces();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Namespaces ret[] = new Namespaces[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Namespaces dto, ResultSet rs) throws SQLException
	{
		dto.setNsId( rs.getInt( COLUMN_NS_ID ) );
		dto.setNamespace( rs.getString( COLUMN_NAMESPACE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Namespaces dto)
	{
	}

	/** 
	 * Returns all rows from the namespaces table that match the specified arbitrary SQL statement
	 */
	public Namespaces[] findByDynamicSelect(String sql, Object[] sqlParams) throws NamespacesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Throwable _e) {
			throw new NamespacesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the namespaces table that match the specified arbitrary SQL statement
	 */
	public Namespaces[] findByDynamicWhere(String sql, Object[] sqlParams) throws NamespacesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Throwable _e) {
			throw new NamespacesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
