/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.jdbc;

import com.wsr.dao.*;
import com.wsr.factory.*;
import com.wsr.dto.*;
import com.wsr.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class PropertyDaoImpl extends AbstractDAO implements PropertyDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT property_ID, property_name, categorisation FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( property_ID, property_name, categorisation ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET property_ID = ?, property_name = ?, categorisation = ? WHERE property_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE property_ID = ?";

	/** 
	 * Index of column property_ID
	 */
	protected static final int COLUMN_PROPERTY_ID = 1;

	/** 
	 * Index of column property_name
	 */
	protected static final int COLUMN_PROPERTY_NAME = 2;

	/** 
	 * Index of column categorisation
	 */
	protected static final int COLUMN_CATEGORISATION = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column property_ID
	 */
	protected static final int PK_COLUMN_PROPERTY_ID = 1;

	/** 
	 * Inserts a new row in the property table.
	 */
	public PropertyPk insert(Property dto) throws PropertyDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getPropertyId() );
			stmt.setString( index++, dto.getPropertyName() );
			stmt.setString( index++, dto.getCategorisation() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			reset(dto);
			return dto.createPk();
		}
		catch (Throwable _e) {
			throw new PropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the property table.
	 */
	public void update(PropertyPk pk, Property dto) throws PropertyDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getPropertyId() );
			stmt.setString( index++, dto.getPropertyName() );
			stmt.setString( index++, dto.getCategorisation() );
			stmt.setInt( 4, pk.getPropertyId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Throwable _e) {
			throw new PropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the property table.
	 */
	public void delete(PropertyPk pk) throws PropertyDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getPropertyId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		}
		catch (Throwable _e) {
			throw new PropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the property table that matches the specified primary-key value.
	 */
	public Property findByPrimaryKey(PropertyPk pk) throws PropertyDaoException
	{
		return findByPrimaryKey( pk.getPropertyId() );
	}

	/** 
	 * Returns all rows from the property table that match the criteria 'property_ID = :propertyId'.
	 */
	public Property findByPrimaryKey(int propertyId) throws PropertyDaoException
	{
		Property ret[] = findByDynamicSelect( SQL_SELECT + " WHERE property_ID = ?", new Object[] {  new Integer(propertyId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the property table that match the criteria ''.
	 */
	public Property[] findAll() throws PropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY property_ID", null );
	}

	/** 
	 * Returns all rows from the property table that match the criteria 'property_ID = :propertyId'.
	 */
	public Property[] findWherePropertyIdEquals(int propertyId) throws PropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE property_ID = ? ORDER BY property_ID", new Object[] {  new Integer(propertyId) } );
	}

	/** 
	 * Returns all rows from the property table that match the criteria 'property_name = :propertyName'.
	 */
	public Property[] findWherePropertyNameEquals(String propertyName) throws PropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE property_name = ? ORDER BY property_name", new Object[] { propertyName } );
	}

	/** 
	 * Returns all rows from the property table that match the criteria 'categorisation = :categorisation'.
	 */
	public Property[] findWhereCategorisationEquals(String categorisation) throws PropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE categorisation = ? ORDER BY categorisation", new Object[] { categorisation } );
	}

	/**
	 * Method 'PropertyDaoImpl'
	 * 
	 */
	public PropertyDaoImpl()
	{
	}

	/**
	 * Method 'PropertyDaoImpl'
	 * 
	 * @param userConn
	 */
	public PropertyDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "webservicerank.property";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Property fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Property dto = new Property();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Property[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Property dto = new Property();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Property ret[] = new Property[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Property dto, ResultSet rs) throws SQLException
	{
		dto.setPropertyId( rs.getInt( COLUMN_PROPERTY_ID ) );
		dto.setPropertyName( rs.getString( COLUMN_PROPERTY_NAME ) );
		dto.setCategorisation( rs.getString( COLUMN_CATEGORISATION ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Property dto)
	{
	}

	/** 
	 * Returns all rows from the property table that match the specified arbitrary SQL statement
	 */
	public Property[] findByDynamicSelect(String sql, Object[] sqlParams) throws PropertyDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Throwable _e) {
			throw new PropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the property table that match the specified arbitrary SQL statement
	 */
	public Property[] findByDynamicWhere(String sql, Object[] sqlParams) throws PropertyDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Throwable _e) {
			throw new PropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
