/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.jdbc;

import com.wsr.dao.*;
import com.wsr.factory.*;
import com.wsr.dto.*;
import com.wsr.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ServicePropertyDaoImpl extends AbstractDAO implements ServicePropertyDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT SP_ID, service_ID, property_ID, property_category FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( SP_ID, service_ID, property_ID, property_category ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET SP_ID = ?, service_ID = ?, property_ID = ?, property_category = ? WHERE SP_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE SP_ID = ?";

	/** 
	 * Index of column SP_ID
	 */
	protected static final int COLUMN_SP_ID = 1;

	/** 
	 * Index of column service_ID
	 */
	protected static final int COLUMN_SERVICE_ID = 2;

	/** 
	 * Index of column property_ID
	 */
	protected static final int COLUMN_PROPERTY_ID = 3;

	/** 
	 * Index of column property_category
	 */
	protected static final int COLUMN_PROPERTY_CATEGORY = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column SP_ID
	 */
	protected static final int PK_COLUMN_SP_ID = 1;

	/** 
	 * Inserts a new row in the service_property table.
	 */
	public ServicePropertyPk insert(ServiceProperty dto) throws ServicePropertyDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getSpId() );
			stmt.setInt( index++, dto.getServiceId() );
			stmt.setInt( index++, dto.getPropertyId() );
			stmt.setInt( index++, dto.getPropertyCategory() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			reset(dto);
			return dto.createPk();
		}
		catch (Throwable _e) {
			throw new ServicePropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the service_property table.
	 */
	public void update(ServicePropertyPk pk, ServiceProperty dto) throws ServicePropertyDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getSpId() );
			stmt.setInt( index++, dto.getServiceId() );
			stmt.setInt( index++, dto.getPropertyId() );
			stmt.setInt( index++, dto.getPropertyCategory() );
			stmt.setInt( 5, pk.getSpId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Throwable _e) {
			throw new ServicePropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the service_property table.
	 */
	public void delete(ServicePropertyPk pk) throws ServicePropertyDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getSpId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		}
		catch (Throwable _e) {
			throw new ServicePropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the service_property table that matches the specified primary-key value.
	 */
	public ServiceProperty findByPrimaryKey(ServicePropertyPk pk) throws ServicePropertyDaoException
	{
		return findByPrimaryKey( pk.getSpId() );
	}

	/** 
	 * Returns all rows from the service_property table that match the criteria 'SP_ID = :spId'.
	 */
	public ServiceProperty findByPrimaryKey(int spId) throws ServicePropertyDaoException
	{
		ServiceProperty ret[] = findByDynamicSelect( SQL_SELECT + " WHERE SP_ID = ?", new Object[] {  new Integer(spId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the service_property table that match the criteria ''.
	 */
	public ServiceProperty[] findAll() throws ServicePropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY SP_ID", null );
	}

	/** 
	 * Returns all rows from the service_property table that match the criteria 'SP_ID = :spId'.
	 */
	public ServiceProperty[] findWhereSpIdEquals(int spId) throws ServicePropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SP_ID = ? ORDER BY SP_ID", new Object[] {  new Integer(spId) } );
	}

	/** 
	 * Returns all rows from the service_property table that match the criteria 'service_ID = :serviceId'.
	 */
	public ServiceProperty[] findWhereServiceIdEquals(int serviceId) throws ServicePropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE service_ID = ? ORDER BY service_ID", new Object[] {  new Integer(serviceId) } );
	}

	/** 
	 * Returns all rows from the service_property table that match the criteria 'property_ID = :propertyId'.
	 */
	public ServiceProperty[] findWherePropertyIdEquals(int propertyId) throws ServicePropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE property_ID = ? ORDER BY property_ID", new Object[] {  new Integer(propertyId) } );
	}

	/** 
	 * Returns all rows from the service_property table that match the criteria 'property_category = :propertyCategory'.
	 */
	public ServiceProperty[] findWherePropertyCategoryEquals(int propertyCategory) throws ServicePropertyDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE property_category = ? ORDER BY property_category", new Object[] {  new Integer(propertyCategory) } );
	}

	/**
	 * Method 'ServicePropertyDaoImpl'
	 * 
	 */
	public ServicePropertyDaoImpl()
	{
	}

	/**
	 * Method 'ServicePropertyDaoImpl'
	 * 
	 * @param userConn
	 */
	public ServicePropertyDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "webservicerank.service_property";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ServiceProperty fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ServiceProperty dto = new ServiceProperty();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ServiceProperty[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ServiceProperty dto = new ServiceProperty();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ServiceProperty ret[] = new ServiceProperty[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ServiceProperty dto, ResultSet rs) throws SQLException
	{
		dto.setSpId( rs.getInt( COLUMN_SP_ID ) );
		dto.setServiceId( rs.getInt( COLUMN_SERVICE_ID ) );
		dto.setPropertyId( rs.getInt( COLUMN_PROPERTY_ID ) );
		dto.setPropertyCategory( rs.getInt( COLUMN_PROPERTY_CATEGORY ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ServiceProperty dto)
	{
	}

	/** 
	 * Returns all rows from the service_property table that match the specified arbitrary SQL statement
	 */
	public ServiceProperty[] findByDynamicSelect(String sql, Object[] sqlParams) throws ServicePropertyDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Throwable _e) {
			throw new ServicePropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the service_property table that match the specified arbitrary SQL statement
	 */
	public ServiceProperty[] findByDynamicWhere(String sql, Object[] sqlParams) throws ServicePropertyDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Throwable _e) {
			throw new ServicePropertyDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
