/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.jdbc;

import com.wsr.dao.*;
import com.wsr.factory.*;
import java.util.Date;
import com.wsr.dto.*;
import com.wsr.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class WsrUsersDaoImpl extends AbstractDAO implements WsrUsersDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT userid, username, password, login_type, name, address, email, reg_date, reffered_by FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( userid, username, password, login_type, name, address, email, reg_date, reffered_by ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET userid = ?, username = ?, password = ?, login_type = ?, name = ?, address = ?, email = ?, reg_date = ?, reffered_by = ? WHERE userid = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE userid = ?";

	/** 
	 * Index of column userid
	 */
	protected static final int COLUMN_USERID = 1;

	/** 
	 * Index of column username
	 */
	protected static final int COLUMN_USERNAME = 2;

	/** 
	 * Index of column password
	 */
	protected static final int COLUMN_PASSWORD = 3;

	/** 
	 * Index of column login_type
	 */
	protected static final int COLUMN_LOGIN_TYPE = 4;

	/** 
	 * Index of column name
	 */
	protected static final int COLUMN_NAME = 5;

	/** 
	 * Index of column address
	 */
	protected static final int COLUMN_ADDRESS = 6;

	/** 
	 * Index of column email
	 */
	protected static final int COLUMN_EMAIL = 7;

	/** 
	 * Index of column reg_date
	 */
	protected static final int COLUMN_REG_DATE = 8;

	/** 
	 * Index of column reffered_by
	 */
	protected static final int COLUMN_REFFERED_BY = 9;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 9;

	/** 
	 * Index of primary-key column userid
	 */
	protected static final int PK_COLUMN_USERID = 1;

	/** 
	 * Inserts a new row in the wsr_users table.
	 */
	public WsrUsersPk insert(WsrUsers dto) throws WsrUsersDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getUserid() );
			stmt.setString( index++, dto.getUsername() );
			stmt.setString( index++, dto.getPassword() );
			stmt.setString( index++, dto.getLoginType() );
			stmt.setString( index++, dto.getName() );
			stmt.setString( index++, dto.getAddress() );
			stmt.setString( index++, dto.getEmail() );
			stmt.setDate(index++, dto.getRegDate()==null ? null : new java.sql.Date( dto.getRegDate().getTime() ) );
			stmt.setInt( index++, dto.getRefferedBy() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setUserid( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Throwable _e) {
			throw new WsrUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the wsr_users table.
	 */
	public void update(WsrUsersPk pk, WsrUsers dto) throws WsrUsersDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getUserid() );
			stmt.setString( index++, dto.getUsername() );
			stmt.setString( index++, dto.getPassword() );
			stmt.setString( index++, dto.getLoginType() );
			stmt.setString( index++, dto.getName() );
			stmt.setString( index++, dto.getAddress() );
			stmt.setString( index++, dto.getEmail() );
			stmt.setDate(index++, dto.getRegDate()==null ? null : new java.sql.Date( dto.getRegDate().getTime() ) );
			stmt.setInt( index++, dto.getRefferedBy() );
			stmt.setInt( 10, pk.getUserid() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
		}
		catch (Throwable _e) {
			throw new WsrUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the wsr_users table.
	 */
	public void delete(WsrUsersPk pk) throws WsrUsersDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getUserid() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
		}
		catch (Throwable _e) {
			throw new WsrUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the wsr_users table that matches the specified primary-key value.
	 */
	public WsrUsers findByPrimaryKey(WsrUsersPk pk) throws WsrUsersDaoException
	{
		return findByPrimaryKey( pk.getUserid() );
	}

	/** 
	 * Returns all rows from the wsr_users table that match the criteria 'userid = :userid'.
	 */
	public WsrUsers findByPrimaryKey(int userid) throws WsrUsersDaoException
	{
		WsrUsers ret[] = findByDynamicSelect( SQL_SELECT + " WHERE userid = ?", new Object[] {  new Integer(userid) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the wsr_users table that match the criteria ''.
	 */
	public WsrUsers[] findAll() throws WsrUsersDaoException
	{
		return findByDynamicSelect( SQL_SELECT, null );
	}

	/**
	 * Method 'WsrUsersDaoImpl'
	 * 
	 */
	public WsrUsersDaoImpl()
	{
	}

	/**
	 * Method 'WsrUsersDaoImpl'
	 * 
	 * @param userConn
	 */
	public WsrUsersDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "webservicerank.wsr_users";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected WsrUsers fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			WsrUsers dto = new WsrUsers();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected WsrUsers[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			WsrUsers dto = new WsrUsers();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		WsrUsers ret[] = new WsrUsers[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(WsrUsers dto, ResultSet rs) throws SQLException
	{
		dto.setUserid( rs.getInt( COLUMN_USERID ) );
		dto.setUsername( rs.getString( COLUMN_USERNAME ) );
		dto.setPassword( rs.getString( COLUMN_PASSWORD ) );
		dto.setLoginType( rs.getString( COLUMN_LOGIN_TYPE ) );
		dto.setName( rs.getString( COLUMN_NAME ) );
		dto.setAddress( rs.getString( COLUMN_ADDRESS ) );
		dto.setEmail( rs.getString( COLUMN_EMAIL ) );
		dto.setRegDate( rs.getDate(COLUMN_REG_DATE ) );
		dto.setRefferedBy( rs.getInt( COLUMN_REFFERED_BY ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(WsrUsers dto)
	{
	}

	/** 
	 * Returns all rows from the wsr_users table that match the specified arbitrary SQL statement
	 */
	public WsrUsers[] findByDynamicSelect(String sql, Object[] sqlParams) throws WsrUsersDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Throwable _e) {
			throw new WsrUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the wsr_users table that match the specified arbitrary SQL statement
	 */
	public WsrUsers[] findByDynamicWhere(String sql, Object[] sqlParams) throws WsrUsersDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Throwable _e) {
			throw new WsrUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
