/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dao;

import com.wsr.dto.*;
import com.wsr.exceptions.*;

public interface ServicecatServiceDao
{
	/** 
	 * Inserts a new row in the servicecat_service table.
	 */
	public ServicecatServicePk insert(ServicecatService dto) throws ServicecatServiceDaoException;

	/** 
	 * Updates a single row in the servicecat_service table.
	 */
	public void update(ServicecatServicePk pk, ServicecatService dto) throws ServicecatServiceDaoException;

	/** 
	 * Deletes a single row in the servicecat_service table.
	 */
	public void delete(ServicecatServicePk pk) throws ServicecatServiceDaoException;

	/** 
	 * Returns the rows from the servicecat_service table that matches the specified primary-key value.
	 */
	public ServicecatService findByPrimaryKey(ServicecatServicePk pk) throws ServicecatServiceDaoException;

	/** 
	 * Returns all rows from the servicecat_service table that match the criteria 'SCS_ID = :scsId'.
	 */
	public ServicecatService findByPrimaryKey(int scsId) throws ServicecatServiceDaoException;

	/** 
	 * Returns all rows from the servicecat_service table that match the criteria ''.
	 */
	public ServicecatService[] findAll() throws ServicecatServiceDaoException;

	/** 
	 * Returns all rows from the servicecat_service table that match the criteria 'SCS_ID = :scsId'.
	 */
	public ServicecatService[] findWhereScsIdEquals(int scsId) throws ServicecatServiceDaoException;

	/** 
	 * Returns all rows from the servicecat_service table that match the criteria 'SC_ID = :scId'.
	 */
	public ServicecatService[] findWhereScIdEquals(int scId) throws ServicecatServiceDaoException;

	/** 
	 * Returns all rows from the servicecat_service table that match the criteria 'service_ID = :serviceId'.
	 */
	public ServicecatService[] findWhereServiceIdEquals(int serviceId) throws ServicecatServiceDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the servicecat_service table that match the specified arbitrary SQL statement
	 */
	public ServicecatService[] findByDynamicSelect(String sql, Object[] sqlParams) throws ServicecatServiceDaoException;

	/** 
	 * Returns all rows from the servicecat_service table that match the specified arbitrary SQL statement
	 */
	public ServicecatService[] findByDynamicWhere(String sql, Object[] sqlParams) throws ServicecatServiceDaoException;

}
