/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dao;

import com.wsr.dto.*;
import com.wsr.exceptions.*;

public interface ServiceCategoryDao
{
	/** 
	 * Inserts a new row in the service_category table.
	 */
	public ServiceCategoryPk insert(ServiceCategory dto) throws ServiceCategoryDaoException;

	/** 
	 * Updates a single row in the service_category table.
	 */
	public void update(ServiceCategoryPk pk, ServiceCategory dto) throws ServiceCategoryDaoException;

	/** 
	 * Deletes a single row in the service_category table.
	 */
	public void delete(ServiceCategoryPk pk) throws ServiceCategoryDaoException;

	/** 
	 * Returns the rows from the service_category table that matches the specified primary-key value.
	 */
	public ServiceCategory findByPrimaryKey(ServiceCategoryPk pk) throws ServiceCategoryDaoException;

	/** 
	 * Returns all rows from the service_category table that match the criteria 'SC_ID = :scId'.
	 */
	public ServiceCategory findByPrimaryKey(int scId) throws ServiceCategoryDaoException;

	/** 
	 * Returns all rows from the service_category table that match the criteria ''.
	 */
	public ServiceCategory[] findAll() throws ServiceCategoryDaoException;

	/** 
	 * Returns all rows from the service_category table that match the criteria 'category_name = :categoryName'.
	 */
	public ServiceCategory[] findWhereCategoryNameEquals(String categoryName) throws ServiceCategoryDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the service_category table that match the specified arbitrary SQL statement
	 */
	public ServiceCategory[] findByDynamicSelect(String sql, Object[] sqlParams) throws ServiceCategoryDaoException;

	/** 
	 * Returns all rows from the service_category table that match the specified arbitrary SQL statement
	 */
	public ServiceCategory[] findByDynamicWhere(String sql, Object[] sqlParams) throws ServiceCategoryDaoException;

}
