/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the namespaces table.
 */
public class NamespacesPk implements Serializable
{
	protected int nsId;

	/** 
	 * This attribute represents whether the primitive attribute nsId is null.
	 */
	protected boolean nsIdNull;

	/** 
	 * Sets the value of nsId
	 */
	public void setNsId(int nsId)
	{
		this.nsId = nsId;
	}

	/** 
	 * Gets the value of nsId
	 */
	public int getNsId()
	{
		return nsId;
	}

	/**
	 * Method 'NamespacesPk'
	 * 
	 */
	public NamespacesPk()
	{
	}

	/**
	 * Method 'NamespacesPk'
	 * 
	 * @param nsId
	 */
	public NamespacesPk(final int nsId)
	{
		this.nsId = nsId;
	}

	/** 
	 * Sets the value of nsIdNull
	 */
	public void setNsIdNull(boolean nsIdNull)
	{
		this.nsIdNull = nsIdNull;
	}

	/** 
	 * Gets the value of nsIdNull
	 */
	public boolean isNsIdNull()
	{
		return nsIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof NamespacesPk)) {
			return false;
		}
		
		final NamespacesPk _cast = (NamespacesPk) _other;
		if (nsId != _cast.nsId) {
			return false;
		}
		
		if (nsIdNull != _cast.nsIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + nsId;
		_hashCode = 29 * _hashCode + (nsIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.NamespacesPk: " );
		ret.append( "nsId=" + nsId );
		return ret.toString();
	}

}
