/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import com.wsr.dao.*;
import com.wsr.factory.*;
import com.wsr.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Namespaces implements Serializable
{
	/** 
	 * This attribute maps to the column ns_id in the namespaces table.
	 */
	protected int nsId;

	/** 
	 * This attribute maps to the column namespace in the namespaces table.
	 */
	protected String namespace;

	/**
	 * Method 'Namespaces'
	 * 
	 */
	public Namespaces()
	{
	}

	/**
	 * Method 'getNsId'
	 * 
	 * @return int
	 */
	public int getNsId()
	{
		return nsId;
	}

	/**
	 * Method 'setNsId'
	 * 
	 * @param nsId
	 */
	public void setNsId(int nsId)
	{
		this.nsId = nsId;
	}

	/**
	 * Method 'getNamespace'
	 * 
	 * @return String
	 */
	public String getNamespace()
	{
		return namespace;
	}

	/**
	 * Method 'setNamespace'
	 * 
	 * @param namespace
	 */
	public void setNamespace(String namespace)
	{
		this.namespace = namespace;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Namespaces)) {
			return false;
		}
		
		final Namespaces _cast = (Namespaces) _other;
		if (nsId != _cast.nsId) {
			return false;
		}
		
		if (namespace == null ? _cast.namespace != namespace : !namespace.equals( _cast.namespace )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + nsId;
		if (namespace != null) {
			_hashCode = 29 * _hashCode + namespace.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return NamespacesPk
	 */
	public NamespacesPk createPk()
	{
		return new NamespacesPk(nsId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.Namespaces: " );
		ret.append( "nsId=" + nsId );
		ret.append( ", namespace=" + namespace );
		return ret.toString();
	}

}
