/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import com.wsr.dao.*;
import com.wsr.factory.*;
import com.wsr.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Property implements Serializable
{
	/** 
	 * This attribute maps to the column property_ID in the property table.
	 */
	protected int propertyId;

	/** 
	 * This attribute maps to the column property_name in the property table.
	 */
	protected String propertyName;

	/** 
	 * This attribute maps to the column categorisation in the property table.
	 */
	protected String categorisation;

	/**
	 * Method 'Property'
	 * 
	 */
	public Property()
	{
	}

	/**
	 * Method 'getPropertyId'
	 * 
	 * @return int
	 */
	public int getPropertyId()
	{
		return propertyId;
	}

	/**
	 * Method 'setPropertyId'
	 * 
	 * @param propertyId
	 */
	public void setPropertyId(int propertyId)
	{
		this.propertyId = propertyId;
	}

	/**
	 * Method 'getPropertyName'
	 * 
	 * @return String
	 */
	public String getPropertyName()
	{
		return propertyName;
	}

	/**
	 * Method 'setPropertyName'
	 * 
	 * @param propertyName
	 */
	public void setPropertyName(String propertyName)
	{
		this.propertyName = propertyName;
	}

	/**
	 * Method 'getCategorisation'
	 * 
	 * @return String
	 */
	public String getCategorisation()
	{
		return categorisation;
	}

	/**
	 * Method 'setCategorisation'
	 * 
	 * @param categorisation
	 */
	public void setCategorisation(String categorisation)
	{
		this.categorisation = categorisation;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Property)) {
			return false;
		}
		
		final Property _cast = (Property) _other;
		if (propertyId != _cast.propertyId) {
			return false;
		}
		
		if (propertyName == null ? _cast.propertyName != propertyName : !propertyName.equals( _cast.propertyName )) {
			return false;
		}
		
		if (categorisation == null ? _cast.categorisation != categorisation : !categorisation.equals( _cast.categorisation )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + propertyId;
		if (propertyName != null) {
			_hashCode = 29 * _hashCode + propertyName.hashCode();
		}
		
		if (categorisation != null) {
			_hashCode = 29 * _hashCode + categorisation.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PropertyPk
	 */
	public PropertyPk createPk()
	{
		return new PropertyPk(propertyId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.Property: " );
		ret.append( "propertyId=" + propertyId );
		ret.append( ", propertyName=" + propertyName );
		ret.append( ", categorisation=" + categorisation );
		return ret.toString();
	}

}
