/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the property table.
 */
public class PropertyPk implements Serializable
{
	protected int propertyId;

	/** 
	 * This attribute represents whether the primitive attribute propertyId is null.
	 */
	protected boolean propertyIdNull;

	/** 
	 * Sets the value of propertyId
	 */
	public void setPropertyId(int propertyId)
	{
		this.propertyId = propertyId;
	}

	/** 
	 * Gets the value of propertyId
	 */
	public int getPropertyId()
	{
		return propertyId;
	}

	/**
	 * Method 'PropertyPk'
	 * 
	 */
	public PropertyPk()
	{
	}

	/**
	 * Method 'PropertyPk'
	 * 
	 * @param propertyId
	 */
	public PropertyPk(final int propertyId)
	{
		this.propertyId = propertyId;
	}

	/** 
	 * Sets the value of propertyIdNull
	 */
	public void setPropertyIdNull(boolean propertyIdNull)
	{
		this.propertyIdNull = propertyIdNull;
	}

	/** 
	 * Gets the value of propertyIdNull
	 */
	public boolean isPropertyIdNull()
	{
		return propertyIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PropertyPk)) {
			return false;
		}
		
		final PropertyPk _cast = (PropertyPk) _other;
		if (propertyId != _cast.propertyId) {
			return false;
		}
		
		if (propertyIdNull != _cast.propertyIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + propertyId;
		_hashCode = 29 * _hashCode + (propertyIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.PropertyPk: " );
		ret.append( "propertyId=" + propertyId );
		return ret.toString();
	}

}
