/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import com.wsr.dao.*;
import com.wsr.factory.*;
import com.wsr.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Resources implements Serializable
{
	/** 
	 * This attribute maps to the column res_id in the resources table.
	 */
	protected int resId;

	/** 
	 * This attribute maps to the column property_ID in the resources table.
	 */
	protected int propertyId;

	/** 
	 * This attribute maps to the column resource in the resources table.
	 */
	protected String resource;

	/** 
	 * This attribute maps to the column ns_id in the resources table.
	 */
	protected int nsId;

	/**
	 * Method 'Resources'
	 * 
	 */
	public Resources()
	{
	}

	/**
	 * Method 'getResId'
	 * 
	 * @return int
	 */
	public int getResId()
	{
		return resId;
	}

	/**
	 * Method 'setResId'
	 * 
	 * @param resId
	 */
	public void setResId(int resId)
	{
		this.resId = resId;
	}

	/**
	 * Method 'getPropertyId'
	 * 
	 * @return int
	 */
	public int getPropertyId()
	{
		return propertyId;
	}

	/**
	 * Method 'setPropertyId'
	 * 
	 * @param propertyId
	 */
	public void setPropertyId(int propertyId)
	{
		this.propertyId = propertyId;
	}

	/**
	 * Method 'getResource'
	 * 
	 * @return String
	 */
	public String getResource()
	{
		return resource;
	}

	/**
	 * Method 'setResource'
	 * 
	 * @param resource
	 */
	public void setResource(String resource)
	{
		this.resource = resource;
	}

	/**
	 * Method 'getNsId'
	 * 
	 * @return int
	 */
	public int getNsId()
	{
		return nsId;
	}

	/**
	 * Method 'setNsId'
	 * 
	 * @param nsId
	 */
	public void setNsId(int nsId)
	{
		this.nsId = nsId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Resources)) {
			return false;
		}
		
		final Resources _cast = (Resources) _other;
		if (resId != _cast.resId) {
			return false;
		}
		
		if (propertyId != _cast.propertyId) {
			return false;
		}
		
		if (resource == null ? _cast.resource != resource : !resource.equals( _cast.resource )) {
			return false;
		}
		
		if (nsId != _cast.nsId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + resId;
		_hashCode = 29 * _hashCode + propertyId;
		if (resource != null) {
			_hashCode = 29 * _hashCode + resource.hashCode();
		}
		
		_hashCode = 29 * _hashCode + nsId;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ResourcesPk
	 */
	public ResourcesPk createPk()
	{
		return new ResourcesPk(resId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.Resources: " );
		ret.append( "resId=" + resId );
		ret.append( ", propertyId=" + propertyId );
		ret.append( ", resource=" + resource );
		ret.append( ", nsId=" + nsId );
		return ret.toString();
	}

}
