/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the service_category table.
 */
public class ServiceCategoryPk implements Serializable
{
	protected int scId;

	/** 
	 * This attribute represents whether the primitive attribute scId is null.
	 */
	protected boolean scIdNull;

	/** 
	 * Sets the value of scId
	 */
	public void setScId(int scId)
	{
		this.scId = scId;
	}

	/** 
	 * Gets the value of scId
	 */
	public int getScId()
	{
		return scId;
	}

	/**
	 * Method 'ServiceCategoryPk'
	 * 
	 */
	public ServiceCategoryPk()
	{
	}

	/**
	 * Method 'ServiceCategoryPk'
	 * 
	 * @param scId
	 */
	public ServiceCategoryPk(final int scId)
	{
		this.scId = scId;
	}

	/** 
	 * Sets the value of scIdNull
	 */
	public void setScIdNull(boolean scIdNull)
	{
		this.scIdNull = scIdNull;
	}

	/** 
	 * Gets the value of scIdNull
	 */
	public boolean isScIdNull()
	{
		return scIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ServiceCategoryPk)) {
			return false;
		}
		
		final ServiceCategoryPk _cast = (ServiceCategoryPk) _other;
		if (scId != _cast.scId) {
			return false;
		}
		
		if (scIdNull != _cast.scIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + scId;
		_hashCode = 29 * _hashCode + (scIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.ServiceCategoryPk: " );
		ret.append( "scId=" + scId );
		return ret.toString();
	}

}
