/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import com.wsr.dao.*;
import com.wsr.factory.*;
import com.wsr.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ServiceProperty implements Serializable
{
	/** 
	 * This attribute maps to the column SP_ID in the service_property table.
	 */
	protected int spId;

	/** 
	 * This attribute maps to the column service_ID in the service_property table.
	 */
	protected int serviceId;

	/** 
	 * This attribute maps to the column property_ID in the service_property table.
	 */
	protected int propertyId;

	/** 
	 * This attribute maps to the column property_category in the service_property table.
	 */
	protected int propertyCategory;

	/**
	 * Method 'ServiceProperty'
	 * 
	 */
	public ServiceProperty()
	{
	}

	/**
	 * Method 'getSpId'
	 * 
	 * @return int
	 */
	public int getSpId()
	{
		return spId;
	}

	/**
	 * Method 'setSpId'
	 * 
	 * @param spId
	 */
	public void setSpId(int spId)
	{
		this.spId = spId;
	}

	/**
	 * Method 'getServiceId'
	 * 
	 * @return int
	 */
	public int getServiceId()
	{
		return serviceId;
	}

	/**
	 * Method 'setServiceId'
	 * 
	 * @param serviceId
	 */
	public void setServiceId(int serviceId)
	{
		this.serviceId = serviceId;
	}

	/**
	 * Method 'getPropertyId'
	 * 
	 * @return int
	 */
	public int getPropertyId()
	{
		return propertyId;
	}

	/**
	 * Method 'setPropertyId'
	 * 
	 * @param propertyId
	 */
	public void setPropertyId(int propertyId)
	{
		this.propertyId = propertyId;
	}

	/**
	 * Method 'getPropertyCategory'
	 * 
	 * @return int
	 */
	public int getPropertyCategory()
	{
		return propertyCategory;
	}

	/**
	 * Method 'setPropertyCategory'
	 * 
	 * @param propertyCategory
	 */
	public void setPropertyCategory(int propertyCategory)
	{
		this.propertyCategory = propertyCategory;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ServiceProperty)) {
			return false;
		}
		
		final ServiceProperty _cast = (ServiceProperty) _other;
		if (spId != _cast.spId) {
			return false;
		}
		
		if (serviceId != _cast.serviceId) {
			return false;
		}
		
		if (propertyId != _cast.propertyId) {
			return false;
		}
		
		if (propertyCategory != _cast.propertyCategory) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + spId;
		_hashCode = 29 * _hashCode + serviceId;
		_hashCode = 29 * _hashCode + propertyId;
		_hashCode = 29 * _hashCode + propertyCategory;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ServicePropertyPk
	 */
	public ServicePropertyPk createPk()
	{
		return new ServicePropertyPk(spId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.ServiceProperty: " );
		ret.append( "spId=" + spId );
		ret.append( ", serviceId=" + serviceId );
		ret.append( ", propertyId=" + propertyId );
		ret.append( ", propertyCategory=" + propertyCategory );
		return ret.toString();
	}

}
