/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import com.wsr.dao.*;
import com.wsr.factory.*;
import com.wsr.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ServicecatService implements Serializable
{
	/** 
	 * This attribute maps to the column SCS_ID in the servicecat_service table.
	 */
	protected int scsId;

	/** 
	 * This attribute maps to the column SC_ID in the servicecat_service table.
	 */
	protected int scId;

	/** 
	 * This attribute maps to the column service_ID in the servicecat_service table.
	 */
	protected int serviceId;

	/**
	 * Method 'ServicecatService'
	 * 
	 */
	public ServicecatService()
	{
	}

	/**
	 * Method 'getScsId'
	 * 
	 * @return int
	 */
	public int getScsId()
	{
		return scsId;
	}

	/**
	 * Method 'setScsId'
	 * 
	 * @param scsId
	 */
	public void setScsId(int scsId)
	{
		this.scsId = scsId;
	}

	/**
	 * Method 'getScId'
	 * 
	 * @return int
	 */
	public int getScId()
	{
		return scId;
	}

	/**
	 * Method 'setScId'
	 * 
	 * @param scId
	 */
	public void setScId(int scId)
	{
		this.scId = scId;
	}

	/**
	 * Method 'getServiceId'
	 * 
	 * @return int
	 */
	public int getServiceId()
	{
		return serviceId;
	}

	/**
	 * Method 'setServiceId'
	 * 
	 * @param serviceId
	 */
	public void setServiceId(int serviceId)
	{
		this.serviceId = serviceId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ServicecatService)) {
			return false;
		}
		
		final ServicecatService _cast = (ServicecatService) _other;
		if (scsId != _cast.scsId) {
			return false;
		}
		
		if (scId != _cast.scId) {
			return false;
		}
		
		if (serviceId != _cast.serviceId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + scsId;
		_hashCode = 29 * _hashCode + scId;
		_hashCode = 29 * _hashCode + serviceId;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ServicecatServicePk
	 */
	public ServicecatServicePk createPk()
	{
		return new ServicecatServicePk(scsId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.ServicecatService: " );
		ret.append( "scsId=" + scsId );
		ret.append( ", scId=" + scId );
		ret.append( ", serviceId=" + serviceId );
		return ret.toString();
	}

}
