/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the servicecat_service table.
 */
public class ServicecatServicePk implements Serializable
{
	protected int scsId;

	/** 
	 * This attribute represents whether the primitive attribute scsId is null.
	 */
	protected boolean scsIdNull;

	/** 
	 * Sets the value of scsId
	 */
	public void setScsId(int scsId)
	{
		this.scsId = scsId;
	}

	/** 
	 * Gets the value of scsId
	 */
	public int getScsId()
	{
		return scsId;
	}

	/**
	 * Method 'ServicecatServicePk'
	 * 
	 */
	public ServicecatServicePk()
	{
	}

	/**
	 * Method 'ServicecatServicePk'
	 * 
	 * @param scsId
	 */
	public ServicecatServicePk(final int scsId)
	{
		this.scsId = scsId;
	}

	/** 
	 * Sets the value of scsIdNull
	 */
	public void setScsIdNull(boolean scsIdNull)
	{
		this.scsIdNull = scsIdNull;
	}

	/** 
	 * Gets the value of scsIdNull
	 */
	public boolean isScsIdNull()
	{
		return scsIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ServicecatServicePk)) {
			return false;
		}
		
		final ServicecatServicePk _cast = (ServicecatServicePk) _other;
		if (scsId != _cast.scsId) {
			return false;
		}
		
		if (scsIdNull != _cast.scsIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + scsId;
		_hashCode = 29 * _hashCode + (scsIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.ServicecatServicePk: " );
		ret.append( "scsId=" + scsId );
		return ret.toString();
	}

}
