/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.wsr.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the service table.
 */
public class ServicePk implements Serializable
{
	protected int serviceId;

	/** 
	 * This attribute represents whether the primitive attribute serviceId is null.
	 */
	protected boolean serviceIdNull;

	/** 
	 * Sets the value of serviceId
	 */
	public void setServiceId(int serviceId)
	{
		this.serviceId = serviceId;
	}

	/** 
	 * Gets the value of serviceId
	 */
	public int getServiceId()
	{
		return serviceId;
	}

	/**
	 * Method 'ServicePk'
	 * 
	 */
	public ServicePk()
	{
	}

	/**
	 * Method 'ServicePk'
	 * 
	 * @param serviceId
	 */
	public ServicePk(final int serviceId)
	{
		this.serviceId = serviceId;
	}

	/** 
	 * Sets the value of serviceIdNull
	 */
	public void setServiceIdNull(boolean serviceIdNull)
	{
		this.serviceIdNull = serviceIdNull;
	}

	/** 
	 * Gets the value of serviceIdNull
	 */
	public boolean isServiceIdNull()
	{
		return serviceIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ServicePk)) {
			return false;
		}
		
		final ServicePk _cast = (ServicePk) _other;
		if (serviceId != _cast.serviceId) {
			return false;
		}
		
		if (serviceIdNull != _cast.serviceIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + serviceId;
		_hashCode = 29 * _hashCode + (serviceIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.wsr.dto.ServicePk: " );
		ret.append( "serviceId=" + serviceId );
		return ret.toString();
	}

}
